NomiProProject/Controllers/WorkingInformationController.cs
using NomiProProject.Models;
using NomiProProject.ViewModel;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace NomiProProject.Controllers
{
    public class WorkingInformationController : Controller
    {
        private NomiProEntities db = new NomiProEntities();

        // GET: WorkingInformation
        public ActionResult Information(string numero_documento)
        {
            Empleado empleado = db.Empleadoes.FirstOrDefault(e => e.Numero_Documento == numero_documento);

            EmployeeInformationViewModel employeeInformationViewModel = new EmployeeInformationViewModel();

            List<SelectListItem> cargos = new List<SelectListItem>();
            List<SelectListItem> jornada = new List<SelectListItem>();

            var Cargos = db.Cargoes.ToList();

            Cargos.ForEach(c =>
            cargos.Add(new SelectListItem {
                Text = c.Descripción_Cargo,
                Value = c.ID_Cargo.ToString()
            }));

            var Jornada = db.Jornadas.ToList();

            Jornada.ForEach(j =>
            jornada.Add(new SelectListItem
            {
                Text = j.Nombre,
                Value = j.ID_Jornada.ToString()
            }));

            employeeInformationViewModel.Jornada = jornada;
            employeeInformationViewModel.Cargos = cargos;
            employeeInformationViewModel.Id_Empleado = empleado.ID_Empleado;
            employeeInformationViewModel.Numero_Documento = numero_documento;
            employeeInformationViewModel.Nombre = empleado.Nombre;
            employeeInformationViewModel.Apellido = empleado.Apellido;

            return View(employeeInformationViewModel);
        }

        public ActionResult Nombre(string Numero_Documento )
        {
           
            Empleado empleado = db.Empleadoes.Find(Numero_Documento);
            if (Numero_Documento == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // GET: WorkingInformation/Create
        public ActionResult Create()
        {
            ViewBag.ID_Nomina = new SelectList(db.Empleadoes, "ID_Empleado", "Documento");
            return View();
        }

        // POST: WorkingInformation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Nomina,Total_Horas_Laboradas,Extras_Diurnas,Extras_Nocturnas,Fecha_Inicial_Pago,Fecha_Final_Pago")] Nomina nomina)
        {
            if (ModelState.IsValid)
            {
                db.Nominas.Add(nomina);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Nomina = new SelectList(db.Empleadoes, "ID_Empleado", "Documento", nomina.ID_Nomina);
            return View(nomina);
        }

        // GET: WorkingInformation/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nomina nomina = db.Nominas.Find(id);
            if (nomina == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Nomina = new SelectList(db.Empleadoes, "ID_Empleado", "Documento", nomina.ID_Nomina);
            return View(nomina);
        }

        // POST: WorkingInformation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Nomina,Total_Horas_Laboradas,Extras_Diurnas,Extras_Nocturnas,Fecha_Inicial_Pago,Fecha_Final_Pago")] Nomina nomina)
        {
            EmployeeInformationViewModel employeeInformationViewModel = new EmployeeInformationViewModel();

            if (ModelState.IsValid)
            {
                db.Entry(nomina).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Nomina = new SelectList(db.Empleadoes, "ID_Empleado", "Documento", nomina.ID_Nomina);
            return View(employeeInformationViewModel);
        }

        // GET: WorkingInformation/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nomina nomina = db.Nominas.Find(id);
            if (nomina == null)
            {
                return HttpNotFound();
            }
            return View(nomina);
        }

        // POST: WorkingInformation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Nomina nomina = db.Nominas.Find(id);
            db.Nominas.Remove(nomina);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Guardar([Bind(Include = "Salario_Basico,Nombre,TipoContrato,Fecha_Inicio,Id_Cargo,Id_jornada,Id_Empleado")] EmployeeInformationViewModel information)
        {
            if (ModelState.IsValid)
            {
                Cargo_Empleado cargo_Empleado = new Cargo_Empleado
                {
                    ID_Empleado = information.Id_Empleado,
                    ID_Cargo = int.Parse(information.Id_Cargo),
                    Fecha_Inicio = information.Fecha_Inicio,
                    Salario_Basico = information.Salario_Basico,
                    TipoContrato = information.TipoContrato,
                    ID_Jornada = information.Id_Jornada
                };

                db.Cargo_Empleado.Add(cargo_Empleado);
                db.SaveChanges();
                return RedirectToAction("SearchEmployee","Employee");
            }

            return View("Information");
        }
    }
}

NomiProProject/Views/WorkingInformation/Information.cshtml
@using NomiProProject.Shared.Enums

@{@model NomiProProject.ViewModel.EmployeeInformationViewModel

ViewBag.Title = "Information";}



<body>

    <section>
        <div class="container-fluid">
            <div class="page-header">
                <h1 class="text-titles"><i class="zmdi zmdi-account zmdi-hc-fw"></i> Información Laboral <small>NomiPro</small></h1>
            </div>
        </div>


        <div class="panel panel-success" ,class="col-xl-3 col-md-6">
            <div class="panel-heading" style="color:#000000">
                <h3 class="panel-title"><i class="zmdi zmdi-male-female"></i> &nbsp; Informacion Empleado</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-6 col-sm-3">
                <div class="control-group">
                    <div class="controls">
                        @Html.LabelFor(model => model.Numero_Documento, htmlAttributes: new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.Numero_Documento, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="col-xs-6 col-sm-3">
                <div class="control-group">
                    <div class="controls">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="col-xs-6 col-sm-3">
                <div class="control-group">
                    <div class="controls">
                        @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.Apellido, new { @class = "form-control" })
                    </div>
                </div>
            </div>

        </div>


        <div class="panel-body" style="overflow-y:scroll; height:330px">
            @using (Html.BeginForm("Guardar", "WorkingInformation", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="row">

                    <div class="container-fluid">
                        <div class="row">

                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group label-floating">
                                    @Html.LabelFor(model => model.Id_Cargo, htmlAttributes: new { @class = "control-label" })
                                    @Html.DropDownListFor(x => Model.Id_Cargo, new SelectList(Model.Cargos, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "Cargo" })
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group label-floating">
                                    @Html.LabelFor(model => model.Salario_Basico, htmlAttributes: new { @class = "control-label" })
                                    @Html.TextBoxFor(model => model.Salario_Basico, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group label-floating">
                                    @Html.LabelFor(model => model.Id_Jornada, htmlAttributes: new { @class = "control-label" })
                                    @Html.DropDownListFor(x => Model.Id_Jornada, new SelectList(Model.Jornada, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "Jornada" })
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group label-floating">
                                    @Html.LabelFor(model => model.TipoContrato, htmlAttributes: new { @class = "control-label" })
                                    @Html.DropDownListFor(model => model.TipoContrato, new SelectList(Enum.GetValues(typeof(ContractType))),
                                            "", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group label-floating">
                                    @Html.LabelFor(model => model.Fecha_Inicio, htmlAttributes: new { @class = "control-label" })
                                    @Html.TextBoxFor(model => model.Fecha_Inicio, new { @class = "form-control", required = "required", @type = "Date" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group label-floating">
                                    @Html.LabelFor(model => model.Fecha_Terminacion, htmlAttributes: new { @class = "control-label" })
                                    @Html.TextBoxFor(model => model.Fecha_Terminacion, new { @class = "form-control", @type = "Date" })
                                </div>
                            </div>
                        </div>

                        <div class="text-center">
                            <div class="margin-top: 20px">
                                <input type="submit" value="Guardar" class="btn btn-success btn-raised btn-sm" style="color:#000000" />

                            </div>
                        </div>

                        <a href="@Url.Action("Index", "Employee")" class="btn btn-info" style="color:#000000">
                            <i class="zmdi zmdi-arrow-left"></i> &nbsp; Volver
                        </a>

                        @Html.HiddenFor(model => model.Id_Empleado)

                    </div>

                </div>


            }

        </div>
    </section>


</body>