NomiProProject/Controllers/CrudController.cs
using System.Data.Entity;
using NomiProProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;



namespace NomiProProject.Controllers
{
    public class CrudController : Controller
    {
        private NomiProEntities db = new NomiProEntities();


        // GET: Crud/Details/5
        public ActionResult Details(int id)
        {            
            Empleado empleado = db.Empleadoes.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }


        public ActionResult Inactive(int id)
        {
            Empleado empleado = db.Empleadoes.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }


        // GET: Crud/Edit/5
        public ActionResult Edit(int id)
        {
            var empleado = db.Empleadoes.FirstOrDefault(e => e.ID_Empleado == id);
            return View(empleado);
        }

        // POST: Crud/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "ID_Empleado, Documento, Numero_Documento, Nombre, Apellido, Genero, Estado")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListEmployee", "Employee");
            }

            return View(empleado);
        }




        // GET: Crud/Edit/5
        public ActionResult PositionEdit(int id)
        {
            var cargo = db.Cargoes.FirstOrDefault(e => e.ID_Cargo == id);
            return View(cargo);
        }

        // POST: Crud/Edit/5
        [HttpPost]
        public ActionResult PositionEdit([Bind(Include = "ID_Cargo, Descripción_Cargo, Rango_Minimo_Salario, Rango_Maximo_Salario")] Cargo cargo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cargo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Position", "Position");
            }

            return View(cargo);
        }

    }
}

NomiProProject/Controllers/EmployeeController.cs
using NomiProProject.Models;
using System.Linq;
using System.Web.Mvc;
using NomiProProject.ViewModel;



namespace NomiProProject.Controllers
{
    public class EmployeeController : Controller
    {
        private NomiProEntities db = new NomiProEntities();
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Crear([Bind(Include = "Documento,Numero_Documento,Nombre,Apellido,Genero,Estado")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                db.Empleadoes.Add(empleado);
                db.SaveChanges();
                return RedirectToAction("NewEmployee");
            }

            return View(empleado);
        }

        public ActionResult NewEmployee()
        {
            return View();
        }



        // GET: Employee/Details/5
        public ActionResult ListEmployee()
        {
            var a = db.Empleadoes.ToList();
            return View(a);
        }

        // GET: Employee/Create
        public ActionResult SearchEmployee()
        {
            if (TempData["Error"] != null && !string.IsNullOrEmpty(TempData["Error"].ToString()))
            {
                ViewBag.Error = TempData["Error"].ToString();
            }

            return View();
        }       
              

        public ActionResult Buscar([Bind(Include = "Numero_Documento")] SearchEmployeeViewModel searchEmployeeViewModel)
        {
            Empleado empleado = db.Empleadoes.FirstOrDefault(e => e.Numero_Documento == searchEmployeeViewModel.Numero_Documento);
            if (empleado == null)
            {
                TempData["Error"] = "EMPLEADO NO ENCONTRADO"; 

                return RedirectToAction("SearchEmployee");
            }

            return RedirectToAction("Information", "WorkingInformation", new { searchEmployeeViewModel.Numero_Documento });
        }


    }
}

NomiProProject/Controllers/RosterController.cs
using NomiProProject.Models;
using NomiProProject.Shared.Enums;
using NomiProProject.ViewModel;
using System.Linq;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;
using System;
using System.Reflection;

namespace NomiProProject.Controllers
{

    public class RosterController : Controller
    {
        private NomiProEntities db = new NomiProEntities();


        public ActionResult Index(int id)
        {
            Empleado empleado = db.Empleadoes.Find(id);

            if (empleado == null)
            {
                return HttpNotFound();
            }

            NominaViewModel nomina = new NominaViewModel();
            var cargoEmpleado = empleado.Cargo_Empleado.FirstOrDefault();

            nomina.Nombre = empleado.Nombre;
            nomina.Apellido = empleado.Apellido;
            nomina.Numero_Documento = empleado.Numero_Documento;
            nomina.Salario_Basico = cargoEmpleado.Salario_Basico;
            nomina.Cargo = cargoEmpleado.Cargo.Descripción_Cargo;
            nomina.Jornada = cargoEmpleado.Jornada.Nombre;            
            nomina.ID_Empleado = empleado.ID_Empleado;
            

            if (cargoEmpleado.TipoContrato == ContractType.ContratoIndefinido.ToString())
            {
                nomina.Aporte_Salud = nomina.Salario_Basico * (decimal)0.04;
                nomina.Aporte_Pension = nomina.Salario_Basico * (decimal)0.04;
            }

            if (nomina.Salario_Basico <= 1656232)
            {
                nomina.AuxilioTransporte += 97032;
            }

            if (TempData["Error"] != null && !string.IsNullOrEmpty(TempData["Error"].ToString()))
            {
                ViewBag.Error = TempData["Error"].ToString();
            }

            return View(nomina);
        }

        public ActionResult Guardar([Bind(Include = "Total_Horas_Laboradas,Extras_Diurnas,Extras_Nocturnas,Fecha_Inicial_Pago, Fecha_Final_Pago,ID_Empleado,Aporte_Salud,Aporte_Pension")] NominaViewModel infonomina)
        {
            if (ModelState.IsValid)
            {
                var fecha_inicio_empleado = db.Empleadoes.FirstOrDefault(e => e.ID_Empleado == infonomina.ID_Empleado).Cargo_Empleado.FirstOrDefault().Fecha_Inicio;

                Nomina nomina = new Nomina
                {
                    Total_Horas_Laboradas = infonomina.Total_Horas_Laboradas,
                    Extras_Diurnas = infonomina.Extras_Diurnas,
                    Extras_Nocturnas = infonomina.Extras_Nocturnas,
                    Fecha_Inicial_Pago = infonomina.Fecha_Inicial_Pago,
                    Fecha_Final_Pago = infonomina.Fecha_Final_Pago,
                    ID_Empleado = infonomina.ID_Empleado,
                    Aporte_Salud = infonomina.Aporte_Salud,
                    Aporte_Pension = infonomina.Aporte_Pension
                };

                if(fecha_inicio_empleado > infonomina.Fecha_Inicial_Pago)
                {
                    TempData["Error"] = "FUERA DEL RANGO DE PAGO";

                    return RedirectToAction("Index", new { id = infonomina.ID_Empleado });
                }

                db.Nominas.Add(nomina);
                db.SaveChanges();

                return RedirectToAction("ListEmployee", "Employee");
            }           

            return View("ListEmployee", "Employee");
        }

        private string MapPath(string seedFile)
        {
            var absolutePath = new Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath; //was AbsolutePath but didn't work with spaces according to comments
            var directoryName = Path.GetDirectoryName(absolutePath);
            var path = Path.Combine(directoryName, ".." + seedFile.TrimStart('~').Replace('/', '\\'));

            return path;
        }

        public ActionResult Imprimir(int id)
        {
            var empleado = db.Empleadoes.FirstOrDefault(e => e.ID_Empleado == id);
            var cargoEmpleado = empleado.Cargo_Empleado.FirstOrDefault();
            var nomina = empleado.Nominas.FirstOrDefault();

            decimal recargo = 0;
            decimal auxilioTransporte = 0;

            if (cargoEmpleado.ID_Jornada == (int)WorkingDay.Night)
            {
                recargo = CalcularRecargoNocturno(cargoEmpleado.Salario_Basico, nomina.Extras_Nocturnas);
            }
            

            if (cargoEmpleado.Salario_Basico <= 1656232)
            {
                auxilioTransporte += 97032;
            }

            var horasextrasdiurnas = CalcularExtrasDiurnas(cargoEmpleado.Salario_Basico, nomina.Extras_Diurnas);

            var TotalDevengado = cargoEmpleado.Salario_Basico + recargo + horasextrasdiurnas + auxilioTransporte
                - empleado.Nominas.FirstOrDefault().Aporte_Salud - empleado.Nominas.FirstOrDefault().Aporte_Pension;

            

            iTextSharp.text.Document doc = new iTextSharp.text.Document();
            PdfWriter.GetInstance(doc, new FileStream($"{MapPath("~/Pdf")}/hola.pdf", FileMode.Create));
            doc.Open();

            Paragraph title = new Paragraph();
            title.Font = FontFactory.GetFont(FontFactory.TIMES, 18f, BaseColor.BLUE);
            title.Add("NomiProSA");
            doc.Add(title); doc.Add(new Paragraph("NIT: 900565456-9"));
            doc.Add(new Paragraph("CORREO:  nomiprosa@gmail.com"));
            doc.Add(new Paragraph("Direccion:  Calle 8 sur # 78-67"));
            doc.Add(new Paragraph("-------------------------------------------------------------------------------------------------------------------------------"));

            doc.Add(new Paragraph($"Empleado: {empleado.Apellido} {empleado.Nombre}"));
            doc.Add(new Paragraph("Documento de Identidad:" + empleado.Numero_Documento));
            doc.Add(new Paragraph("Básico:" + empleado.Cargo_Empleado.FirstOrDefault().Salario_Basico));
            doc.Add(new Paragraph("Cargo:" + cargoEmpleado.Cargo.Descripción_Cargo));
            doc.Add(new Paragraph("Cargo:" + cargoEmpleado.TipoContrato));
            doc.Add(new Paragraph("Jornada:" + cargoEmpleado.Jornada.Nombre));
            doc.Add(new Paragraph("Periodo de Liquidacion Inicial:" + empleado.Nominas.LastOrDefault().Fecha_Inicial_Pago));
            doc.Add(new Paragraph("Periodo de Liquidacion Final:" + empleado.Nominas.LastOrDefault().Fecha_Final_Pago));

            doc.Add(new Paragraph("-------------------------------------------------------------------------------------------------------------------------------"));

            
            doc.Add(new Paragraph("Recibo de pago"));
            doc.Add(new Paragraph("========================================================================="));


            PdfPTable table = new PdfPTable(9);

            table.AddCell("Basico");
            table.AddCell("Total Horas");
            table.AddCell("Auxi.Transporte");
            table.AddCell("Salud");
            table.AddCell("Pension");
            table.AddCell("Extras Dia");
            table.AddCell("Extras Noche");
            table.AddCell("Recargo");
            table.AddCell("Neto");






            table.AddCell("" + empleado.Cargo_Empleado.FirstOrDefault().Salario_Basico);
            table.AddCell("" + empleado.Nominas.LastOrDefault().Total_Horas_Laboradas);
            table.AddCell("" + auxilioTransporte);
            table.AddCell("" + nomina.Aporte_Salud);
            table.AddCell("" + nomina.Aporte_Pension);
            table.AddCell("" + nomina.Extras_Diurnas);
            table.AddCell("" + nomina.Extras_Nocturnas);
            table.AddCell("" + recargo);
            table.AddCell("" + TotalDevengado);

           
            doc.Add(table);
            doc.Close();




            // db.Nominas.Add(imprimir);
            //  db.SaveChanges();
            //  return RedirectToAction("Index", "Roster");

            //byte[] fileBytes = System.IO.File.ReadAllBytes($"{MapPath("~/Pdf")}/hola.pdf");
            //string fileName = "myfile.pdf";
            //return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);

            return Redirect("/Pdf/hola.pdf");
        }


        private decimal CalcularRecargoNocturno(decimal Salario_Basico, int? Horas_Extras = 0)
        {
            decimal vhora = Salario_Basico / 240;
            var recarnoc = vhora * (decimal)0.35;
            var extrat = vhora * (decimal)0.75;
            
            return recarnoc + (extrat * (Horas_Extras != null ? (int)Horas_Extras : 0));
        }

        private decimal CalcularExtrasDiurnas(decimal Salario_Basico, int? Extras_Diurnas = 0)
        {
            decimal vhora = Salario_Basico / 240;
            var extraDia = vhora * (decimal)0.25;
            var totalExtra  = extraDia * (Extras_Diurnas != null ? (int)Extras_Diurnas : 0);

            return totalExtra;
        }
    }
}

NomiProProject/Views/Employee/Index.cshtml
@using NomiProProject.Shared.Enums

@{@model NomiProProject.Models.Empleado


ViewBag.Title = "Index";
}

<!-- Content page-->

    <body>
        <section>
            <div class="container-fluid">
                <div class="page-header">
                    <h1 class="text-titles"><i class="zmdi zmdi-account zmdi-hc-fw"></i> Empleado <small>NomiPro</small></h1>
                </div>
            </div>

            <div class="container-fluid">
                <ul class="breadcrumb breadcrumb-tabs">
                    <li>
                        <a href="@Url.Action("NewEmployee", "Employee")" class="btn btn-info" style="color:#000000">
                            <i class="zmdi zmdi-plus"></i> &nbsp; NUEVO EMPLEADO
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("ListEmployee", "Employee")" class="btn btn-success" style="color:#000000">
                            <i class="zmdi zmdi-format-list-bulleted"></i> &nbsp; LISTA DE EMPLEADOS
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("SearchEmployee", "Employee")" class="btn btn-primary" style="color:#000000">
                            <i class="zmdi zmdi-search"></i> &nbsp; BUSCAR EMPLEADO
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Position", "Position")" class="btn btn-danger" style="color:#000000">
                            <i class="zmdi zmdi-comment-list"></i> &nbsp; LISTA  DE CARGOS
                        </a>
                    </li>


                </ul>
            </div>

            <div class="container-fluid">
                <div class="page-header">
                    <h1 class="text-titles">Sistema <small>Horario Empleado</small></h1>
                </div>

                <div class="panel-body" style="overflow-y:scroll; height:290px">

                    <section id="cd-timeline" class="cd-container">
                        <div class="cd-timeline-block">
                            <div class="cd-timeline-img">
                                <img src="/Content/assets/avatars/StudetMaleAvatar.png" alt="user-picture">
                            </div>
                            <div class="cd-timeline-content">
                                <h4 class="text-center text-titles">1 - Nombre (Gerente Proyecto)</h4>
                                <p class="text-center">
                                    <i class="zmdi zmdi-timer zmdi-hc-fw"></i> Comienzo: <em>6:00 AM</em> &nbsp;&nbsp;&nbsp;
                                    <i class="zmdi zmdi-time zmdi-hc-fw"></i> Fin: <em>2:00 PM</em>
                                </p>
                                <span class="cd-date"><i class="zmdi zmdi-calendar-note zmdi-hc-fw"></i>Ingreso 07/07/2016</span>
                            </div>
                        </div>
                        <div class="cd-timeline-block">
                            <div class="cd-timeline-img">
                                <img src="/Content/assets/avatars/StudetFemaleAvatar.png" alt="user-picture">
                            </div>
                            <div class="cd-timeline-content">
                                <h4 class="text-center text-titles">2 - Nombre (Programador)</h4>
                                <p class="text-center">
                                    <i class="zmdi zmdi-timer zmdi-hc-fw"></i> Comienzo: <em>2:00 PM</em> &nbsp;&nbsp;&nbsp;
                                    <i class="zmdi zmdi-time zmdi-hc-fw"></i> Fin: <em>10:00 PM</em>
                                </p>
                                <span class="cd-date"><i class="zmdi zmdi-calendar-note zmdi-hc-fw"></i> Ingraso 20/04/2012</span>
                            </div>
                        </div>
                        <div class="cd-timeline-block">
                            <div class="cd-timeline-img">
                                <img src="~/Content/assets/avatars/TeacherFemaleAvatar.png" alt="user-picture">
                            </div>
                            <div class="cd-timeline-content">
                                <h4 class="text-center text-titles">3 - Nombre (Pruebas)</h4>
                                <p class="text-center">
                                    <i class="zmdi zmdi-timer zmdi-hc-fw"></i> Comienzo: <em>2:00 PM</em> &nbsp;&nbsp;&nbsp;
                                    <i class="zmdi zmdi-time zmdi-hc-fw"></i> Fin: <em>10:00 PM</em>
                                </p>
                                <span class="cd-date"><i class="zmdi zmdi-calendar-note zmdi-hc-fw"></i> Ingreso 24/10/2018</span>
                            </div>
                        </div>
                        <div class="cd-timeline-block">
                            <div class="cd-timeline-img">
                                <img src="~/Content/assets/avatars/TeacherMaleAvatar.png" alt="user-picture">
                            </div>
                            <div class="cd-timeline-content">
                                <h4 class="text-center text-titles">4 - Nombre (Diseñador)</h4>
                                <p class="text-center">
                                    <i class="zmdi zmdi-timer zmdi-hc-fw"></i> Comienzo: <em>6:00 AM</em> &nbsp;&nbsp;&nbsp;
                                    <i class="zmdi zmdi-time zmdi-hc-fw"></i> Fin: <em>2:00 PM</em>
                                </p>
                                <span class="cd-date"><i class="zmdi zmdi-calendar-note zmdi-hc-fw"></i> Ingraso 09/03/2009</span>
                          </div>
                      </div>
                  </section>


                </div>


          </div>

        </section>

 </body>

NomiProProject/Views/Employee/ListEmployee.cshtml
@model IEnumerable<NomiProProject.Models.Empleado>

@{
    ViewBag.Title = "ListEmployee";
}


<body>
    <section>
        <!-- Content page -->
        <div class="container-fluid">
            <div class="page-header">
                <h1 class="text-titles"><i class="zmdi zmdi-account zmdi-hc-fw"></i> Empleado<small>NomiPro</small></h1>
            </div>
        </div>

        <div class="container-fluid">
            <ul class="breadcrumb breadcrumb-tabs">
                <li>
                    <a href="@Url.Action("NewEmployee", "Employee")" class="btn btn-info" style="color:#000000">
                        <i class="zmdi zmdi-plus"></i> &nbsp; NUEVO EMPLEADO
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("ListEmployee", "Employee")" class="btn btn-success" style="color:#000000">
                        <i class="zmdi zmdi-format-list-bulleted"></i> &nbsp; LISTA EMPLEADO
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("SearchEmployee", "Employee")" class="btn btn-primary" style="color:#000000">
                        <i class="zmdi zmdi-search"></i> &nbsp; BUSCAR EMPLEADO
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Position", "Position")" class="btn btn-danger" style="color:#000000">
                        <i class="zmdi zmdi-comment-list"></i> &nbsp; LISTA  DE CARGOS
                    </a>
                </li>
            </ul>
        </div>

        <!-- Panel listado de administradores -->
        <div class="container-fluid">
            <div class="panel panel-success">
                <div class="panel-heading"style="color:#000000">
                    <h3 class="panel-title"><i class="zmdi zmdi-format-list-bulleted"></i> &nbsp; LISTA DE EMPLEADOS</h3>
                </div>
                <div class="panel-body" style="overflow-y:scroll; height:330px">
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-hover text-center">
                                <thead>
                                    <tr>
                                        <th class="text-center">Documento</th>
                                        <th class="text-center">Numero_Documento</th>
                                        <th class="text-center">Nombre</th>
                                        <th class="text-center">Apellido</th>
                                        <th class="text-center">Genero</th>
                                        <th class="text-center">Estado</th>
                                    </tr>
                                </thead>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Documento)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Numero_Documento)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Nombre)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Apellido)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Genero)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Estado)
                                        </td>
                                        <td>
                                            <ul class="breadcrumb breadcrumb-tabs">
                                                <li>
                                                    <a href="@Url.Action("Edit", "Crud", new { id=item.ID_Empleado })" class="btn btn-info" style="color:#000000">
                                                        <i class="zmdi zmdi-border-color"></i> &nbsp; Editar
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("Details", "Crud",new { id=item.ID_Empleado })" class="btn btn-success" style="color:#000000">
                                                        <i class="zmdi zmdi-male-female"></i> &nbsp; Detalles
                                                    </a>
                                                </li>

                                                <li>
                                                    <a href="@Url.Action("Index", "Roster", new { id=item.ID_Empleado })" class="btn btn-primary" style="color:#000000">
                                                        <i class="zmdi zmdi-calendar-note"></i> &nbsp; Nómina
                                                    </a>
                                                </li>

                                            </ul>
                                            <div class="text-center">
                                                <a href="@Url.Action("Imprimir", "Roster", new { id=item.ID_Empleado })" class="btn btn-danger" style="color:#000000">
                                                    <i class="zmdi zmdi-image"></i> &nbsp; Imprimir Nómina
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                }


                            </table>

                        </div>

                    </div>

                </div>

            </div>



        </div>


    </section>

    <!--====== Scripts -->
    <script src="./js/jquery-3.1.1.min.js"></script>
    <script src="./js/sweetalert2.min.js"></script>
    <script src="./js/bootstrap.min.js"></script>
    <script src="./js/material.min.js"></script>
    <script src="./js/ripples.min.js"></script>
    <script src="./js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="./js/main.js"></script>
    <script>
        $.material.init();
    </script>

</body>

NomiProProject/Views/Employee/NewEmployee.cshtml
@using NomiProProject.Shared.Enums


@{@model NomiProProject.Models.Empleado

ViewBag.Title = "NewEmployee";}




<!-- Content page-->
<section>
    <div class="container-fluid">
        <div class="page-header">
            <h1 class="text-titles"><i class="zmdi zmdi-account zmdi-hc-fw"></i> Empleado <small>NomiPro</small></h1>
        </div>
    </div>

    <div class="container-fluid">
        <ul class="breadcrumb breadcrumb-tabs">
            <li>
                <a href="@Url.Action("Index", "Employee")" class="btn btn-info" style="color:#000000">
                    <i class="zmdi zmdi-plus"></i> &nbsp; NUEVO EMPLEADO
                </a>
            </li>
            <li>
                <a href="@Url.Action("ListEmployee", "Employee")" class="btn btn-success" style="color:#000000">
                    <i class="zmdi zmdi-format-list-bulleted"></i> &nbsp; LISTA DE EMPLEADOS
                </a>
            </li>
            <li>
                <a href="@Url.Action("SearchEmployee", "Employee")" class="btn btn-primary" style="color:#000000">
                    <i class="zmdi zmdi-search"></i> &nbsp; BUSCAR EMPLEADO
                </a>
            </li>
            <li>
                <a href="@Url.Action("Position", "Position")" class="btn btn-danger" style="color:#000000">
                    <i class="zmdi zmdi-comment-list"></i> &nbsp; LISTA  DE CARGOS
                </a>
            </li>
        </ul>
    </div>

    <!-- Panel nuevo administrador -->
    <div class="container-fluid">
        <div class="panel panel-info">
            <div class="panel-heading"style="color:#000000">
                <h3 class="panel-title"><i class="zmdi zmdi-plus"></i> &nbsp; Nuevo Empleado </h3>
            </div>
            <div class="panel-body" style="overflow-y:scroll; height:330px">
                @using (Html.BeginForm("Crear", "Employee", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <fieldset>
                        <legend><i class="zmdi zmdi-account-box"></i> &nbsp; Informacion Personal </legend>
                        <div class="container-fluid">
                            <div class="row">

                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group label-floating">
                                        @Html.LabelFor(model => model.Documento, htmlAttributes: new { @class = "control-label" })
                                        @Html.DropDownListFor(model => model.Documento, new SelectList(Enum.GetValues(typeof(Document))),
                                                "", new { @class = "form-control" })
                                    </div>
                                </div>

                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group label-floating">
                                        @Html.LabelFor(model => model.Numero_Documento, htmlAttributes: new { @class = "control-label" })
                                        @Html.TextBoxFor(model => model.Numero_Documento, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group label-floating">
                                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
                                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group label-floating">
                                        @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label" })
                                        @Html.TextBoxFor(model => model.Apellido, new { @class = "form-control" })
                                    </div>
                                </div>

                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group label-floating">
                                        @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label" })
                                        @Html.DropDownListFor(model => model.Genero, new SelectList(Enum.GetValues(typeof(Gender))),
                                                "", new { @class = "form-control" })
                                    </div>
                                </div>

                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group label-floating">
                                        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label" })
                                        @Html.TextBoxFor(model => model.Estado, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="text-center">
                                    <div class="margin-top: 20px">
                                        <input type="submit" value="Crear" class="btn btn-info btn-raised btn-sm" />
                                    </div>
                                </div>                              

                            </div>
                        </div>
                    </fieldset>
                }
            </div>
        </div>
    </div>
</section>